---
- name: Add Caddy signing key
  apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present
    keyring: /usr/share/keyrings/caddy-archive-keyring.gpg

- name: Add Caddy APT repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/caddy-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
    filename: caddy

- name: Install Caddy
  apt:
    name: caddy
    state: present
    update_cache: yes

- name: Template Caddyfile
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "0644"
  notify: Reload Caddy

- name: Enable and start Caddy
  systemd:
    name: caddy
    enabled: yes
    state: started
